### PR TITLE
Adding Postgres operator and hook

### PR DESCRIPTION
**Pull request by kerzhner**
This PR mimics the MySQL operator and hook to create the Postgres operator and hook.

### CODE REVIEW

**Comment by mistercrunch** [comment]
![img] (http://www.reactiongifs.com/r/dstfp.gif)

**Comment by mistercrunch** [comment]
hey quick question about the pysqlite dependency. Do you actually need that?

Apparently sqlite3 is part of the standard python library since python 2.6, so pysqlite shouldn't be needed. Are you on a python2.5 install?

I'd like to kick that dependency out if possible because it requires the C os level libs sqlite-devel or something and I'm un userspace in some of my server so I can't easily add os packages.

**Comment by kerzhner** [comment]
Good catch Max, I don't need that dependency. I am using python 2.7. pysqlite snuck into the diff while I was plying around with the project.

**Comment by mistercrunch** [comment]
Cool. Thank you so much for your contribution!

Oh by the way, did you say this works with Redshift as is?!

**Comment by kerzhner** [comment]
Yep, we are currently using the Postgres operator for regular Redshift ETL jobs.

**Pull request merged**
