### PR TITLE
add sqlite hook

### PR DESCRIPTION
**Pull request by askeys**
@mistercrunch this adds the sqlite hook.  A lot of the code is repeated from the MySQL hook, but there are some differences that made it difficult to make them a single class.  Let me know if this is OK...  I could derive them from a common base if you would prefer.

### CODE REVIEW

**Comment by mistercrunch** [comment]
Awesome! This will be super useful for unit tests, and especially examples, so that I can squeeze parameterized SQL into the examples that ship with Airflow.

This is very nit-picky, but I'm trying to move to use only double quotes for docstrings. 
https://www.python.org/dev/peps/pep-0257/

Do you feel like squeezing some doctests in there? I've been putting some in hooks as I expect people to use hooks in scripts.

**Comment by askeys** [comment]
Tried to add the doctest, but I couldn't get initdb to set up the initial sqlite database correctly.  If you can help me figure that out I will add the test.

**Comment by askeys** [comment]
@mistercrunch ok, added doctests and everything seems to pass.

**Comment by mistercrunch** [comment]
Muy bien. I'm merging this in.

**Comment by mistercrunch** [comment]
Oh somehow the changes to utils.py didn't make it in...

**Comment by askeys** [comment]
Also noticed this.  Just added it in a separate PR.

**Pull request merged**
